<?php 

/**
 * @file
 * Put hybridauth widget at suitable position
 */

/**
 * @Author Kuldeep Singh Pal [TKuldeep]
 * implements hook_form_alter
 */

function alter_hybridauth_form_alter(&$form, &$form_state, $form_id) {

  // hide some field from user edit page 
  if($form_id == "edit_profile_user_profile_form") {
    unset($form['field_twitter_url']);
    unset($form['field_linkedin_url']);
  }

  // hide the user register fields
  if ($form_id == 'user_register_form') {
    // Unset user registration related fields unless user has permission to Administer Users.
    global $user;
    if (!user_access("administer users")) {
      unset($form['field_name_first']);
      unset($form['field_name_last']);
      unset($form['account']['mail']);
      unset($form['actions']['submit']);
    }
  }
  if ($form_id == 'user_login') {
    $form['login_msg'] = array(
      '#markup' =>t('<b>Or login using your email address and password</b>'),
      '#weight' => -40,
    );
  }
}

